REPORT.

* select all corrections to a transport order.

PARAMETERS: T_ORDER LIKE E070-TRKORR.

INITIALIZATION.
  T_ORDER = SY-SYSID.
  T_ORDER+3(2) = 'K%'.

START-OF-SELECTION.
  TABLES: E070, E071.

  DATA: BEGIN OF OUTLINE,
        STRKORR LIKE   E070-STRKORR,
        BLANK1,
        TRKORR  LIKE   E070-TRKORR,
        BLANK2,
        TRSTATUS LIKE  E070-TRSTATUS,
        BLANK3,
        AS4USER LIKE   E070-AS4USER,
        BLANK4,
        AS4DATE LIKE   E070-AS4DATE,
        END OF OUTLINE.
  DATA: OLDKORR LIKE E070-TRKORR.

  CLEAR OUTLINE.
  OUTLINE-STRKORR = TEXT-001.
  OUTLINE-TRKORR = TEXT-002.
  OUTLINE-AS4USER = TEXT-003.
  OUTLINE-AS4DATE = TEXT-004.

  WRITE: / OUTLINE.
  CLEAR OUTLINE.

  SELECT * FROM E070
    WHERE STRKORR LIKE T_ORDER AND TRFUNCTION = 'S'
    ORDER BY STRKORR  TRKORR.

    MOVE-CORRESPONDING E070 TO OUTLINE.
    IF OLDKORR EQ OUTLINE-STRKORR.
      OUTLINE-STRKORR = SPACE.
    ELSE.
      ULINE.
      OLDKORR = E070-STRKORR.
    ENDIF.

    WRITE: / OUTLINE.

  ENDSELECT.
